const CHALLENGES = [
  // ── LEVEL 1: Basic SELECT ──────────────────────────────────────────
  {
    id: 1,
    level: 1,
    levelName: 'Level 1 — Pawfect Basics',
    levelEmoji: '🐾',
    title: "Who's in the Shelter?",
    story: "Welcome, new volunteer! You just walked into PawShelter headquarters on your first day. Before anything else, let's get a full picture of all our furry residents living across our three shelters.",
    task: 'Select <strong>all columns</strong> from the <code>PET</code> table.',
    hint: '<code>SELECT * FROM table_name</code> — the <code>*</code> means "give me every column".',
    canonicalQuery: 'SELECT * FROM PET',
    validateType: 'rowCount',
    expectedCount: 21,
    points: 100,
    successMessage: "You found all 21 of our wonderful residents! Great start, volunteer! 🐕🐈"
  },
  {
    id: 2,
    level: 1,
    levelName: 'Level 1 — Pawfect Basics',
    levelEmoji: '🐾',
    title: 'Our Shelter Locations',
    story: "The director needs a quick overview of all our shelter branches — where they are and how many animals each can hold. Let's pull that information up!",
    task: 'Select <strong>all information</strong> from the <code>SHELTER</code> table.',
    hint: 'Same structure as before, just a different table name.',
    canonicalQuery: 'SELECT * FROM SHELTER',
    validateType: 'rowCount',
    expectedCount: 3,
    points: 100,
    successMessage: "3 shelters across Turkey — Istanbul, Ankara, and Izmir! 🏠🏠🏠"
  },
  {
    id: 3,
    level: 1,
    levelName: 'Level 1 — Pawfect Basics',
    levelEmoji: '🐾',
    title: 'Just Their Names',
    story: "A radio host called and wants to read out the names of all our pets on air to help with adoptions. We only need their names and species — not the full pet file!",
    task: 'Select only the <code>Pet_name</code> and <code>Species</code> columns from the <code>PET</code> table.',
    hint: 'Instead of <code>*</code>, list column names separated by commas: <code>SELECT col1, col2 FROM table</code>',
    canonicalQuery: 'SELECT Pet_name, Species FROM PET',
    validateType: 'columns',
    requiredColumns: ['Pet_name', 'Species'],
    expectedCount: 21,
    points: 150,
    successMessage: "Perfect! The radio host has 21 pets to announce! 📻🎙️"
  },

  // ── LEVEL 2: WHERE Filtering ───────────────────────────────────────
  {
    id: 4,
    level: 2,
    levelName: 'Level 2 — Finding Friends',
    levelEmoji: '🔍',
    title: 'Ready for Adoption!',
    story: "A lovely family just called — they want to adopt a pet TODAY! Show them only the pets that are currently available. No point listing ones that are already adopted or pending review.",
    task: "Select all pets where <code>Adoption_status</code> is <code>'Available'</code>.",
    hint: "Use <code>WHERE column = 'value'</code> to filter rows. Status values: <code>'Available'</code>, <code>'Pending'</code>, <code>'Adopted'</code>",
    canonicalQuery: "SELECT * FROM PET WHERE Adoption_status = 'Available'",
    validateType: 'rowCount',
    expectedCount: 10,
    points: 150,
    successMessage: "10 pets waiting for their forever home! Let's find them a family! 🏡❤️"
  },
  {
    id: 5,
    level: 2,
    levelName: 'Level 2 — Finding Friends',
    levelEmoji: '🔍',
    title: 'Istanbul Branch Report',
    story: "The Istanbul branch manager needs a complete list of all their pets for an upcoming inspection. Istanbul's shelter ID is 1 — filter the pets accordingly!",
    task: 'Select all pets that belong to shelter number <code>1</code>.',
    hint: 'Filter by <code>Shelter_id = 1</code> (no quotes needed for numbers)',
    canonicalQuery: 'SELECT * FROM PET WHERE Shelter_id = 1',
    validateType: 'rowCount',
    expectedCount: 7,
    points: 150,
    successMessage: "7 pets in the Istanbul shelter — report ready! 🌉✅"
  },
  {
    id: 6,
    level: 2,
    levelName: 'Level 2 — Finding Friends',
    levelEmoji: '🔍',
    title: 'Lady Paws Photo Shoot',
    story: "We're organising a special photo shoot for our female pets to boost their adoption chances. Find all the girls! (Hint: there are more than 10 of them!)",
    task: "Select all pets where <code>Sex</code> is <code>'F'</code>.",
    hint: "Filter by the Sex column. Values are <code>'M'</code> or <code>'F'</code>.",
    canonicalQuery: "SELECT * FROM PET WHERE Sex = 'F'",
    validateType: 'rowCount',
    expectedCount: 11,
    points: 150,
    successMessage: "11 lovely ladies ready for their close-up! 📸✨"
  },

  // ── LEVEL 3: ORDER BY & LIMIT ──────────────────────────────────────
  {
    id: 7,
    level: 3,
    levelName: 'Level 3 — Sorting it Out',
    levelEmoji: '↕️',
    title: 'Newest Arrivals',
    story: "Our shelter newsletter wants to feature the 3 most recently arrived pets in this month's issue — they always get the most adoption interest! Find who just joined us.",
    task: 'Select all columns from <code>PET</code>, ordered by <code>Arrival_date</code> from newest to oldest, showing only the top <strong>3</strong>.',
    hint: 'Use <code>ORDER BY column DESC</code> to sort newest first, and <code>LIMIT 3</code> to show only 3 rows.',
    canonicalQuery: 'SELECT * FROM PET ORDER BY Arrival_date DESC LIMIT 3',
    validateType: 'rowCount',
    expectedCount: 3,
    points: 200,
    successMessage: "These 3 are the newest additions to our family — they'll be featured this month! ✨📰"
  },
  {
    id: 8,
    level: 3,
    levelName: 'Level 3 — Sorting it Out',
    levelEmoji: '↕️',
    title: 'Alphabetical Roll Call',
    story: "The adoption fair organiser needs a printed list of all pet names and species in alphabetical order for the event brochure. Sort them A to Z!",
    task: 'Select <code>Pet_name</code> and <code>Species</code> from <code>PET</code>, ordered alphabetically by <code>Pet_name</code>.',
    hint: '<code>ORDER BY column ASC</code> (or just <code>ORDER BY column</code>) sorts A to Z.',
    canonicalQuery: 'SELECT Pet_name, Species FROM PET ORDER BY Pet_name ASC',
    validateType: 'rowCount',
    expectedCount: 21,
    points: 200,
    successMessage: "A perfect A–Z list — ready to print for the fair! 🖨️📋"
  },

  // ── LEVEL 4: Aggregate Functions ──────────────────────────────────
  {
    id: 9,
    level: 4,
    levelName: 'Level 4 — Counting Paws',
    levelEmoji: '📊',
    title: 'Annual Pet Count',
    story: "The director is filing the annual government report and needs one simple number: the total count of all animals in our care across all three shelters.",
    task: 'Write a query that returns the <strong>total count</strong> of all pets.',
    hint: 'Use the <code>COUNT(*)</code> function: <code>SELECT COUNT(*) FROM table</code>',
    canonicalQuery: 'SELECT COUNT(*) FROM PET',
    validateType: 'singleValue',
    expectedValue: '21',
    points: 200,
    successMessage: "21 animals in our care — the director has what she needs! 📋🎉"
  },
  {
    id: 10,
    level: 4,
    levelName: 'Level 4 — Counting Paws',
    levelEmoji: '📊',
    title: 'Adoption Status Breakdown',
    story: "Management needs a full picture of the adoption pipeline: how many pets are available, how many have pending applications, and how many have already been adopted. Group them!",
    task: 'Select <code>Adoption_status</code> and the <strong>count</strong> of pets for each status, grouped by <code>Adoption_status</code>.',
    hint: 'Use <code>GROUP BY</code>: <code>SELECT column, COUNT(*) FROM table GROUP BY column</code>',
    canonicalQuery: 'SELECT Adoption_status, COUNT(*) as Count FROM PET GROUP BY Adoption_status',
    validateType: 'rowCount',
    expectedCount: 3,
    points: 250,
    successMessage: "3 status groups found: Available (10), Pending (5), Adopted (6). Full picture! 📊🐾"
  },

  // ── LEVEL 5: JOINs ────────────────────────────────────────────────
  {
    id: 11,
    level: 5,
    levelName: 'Level 5 — Joining Forces',
    levelEmoji: '🔗',
    title: 'Pets and Their Cities',
    story: "A journalist is writing a story about shelter animals across Turkey and wants to know which pets are in which city. The city info is in the SHELTER table — join it with PET!",
    task: 'Join <code>PET</code> and <code>SHELTER</code> to show <code>Pet_name</code>, <code>Species</code>, and <code>City</code> for each pet.',
    hint: '<code>SELECT cols FROM PET JOIN SHELTER ON PET.Shelter_id = SHELTER.Shelter_id</code>',
    canonicalQuery: 'SELECT P.Pet_name, P.Species, S.City FROM PET P JOIN SHELTER S ON P.Shelter_id = S.Shelter_id',
    validateType: 'rowCount',
    expectedCount: 21,
    points: 300,
    successMessage: "Now we know exactly which city every pet calls home! The journalist is thrilled. 🗺️📰"
  },
  {
    id: 12,
    level: 5,
    levelName: 'Level 5 — Joining Forces',
    levelEmoji: '🔗',
    title: 'Happy Families',
    story: "It's time to celebrate! We want to send thank-you cards to all successful adopters. Show the name of each adopted pet along with their adopter's first name.",
    task: 'Join <code>ADOPTS</code>, <code>PET</code>, and <code>PERSON</code> to show <code>Pet_name</code> and the adopter\'s <code>F_name</code>. Expect 6 rows.',
    hint: 'You need 3 tables: ADOPTS links to PET (via Pet_id) and PERSON (via Adopter_ID). Chain two JOINs.',
    canonicalQuery: 'SELECT P.Pet_name, PR.F_name FROM ADOPTS A JOIN PET P ON A.Pet_id = P.Pet_id JOIN PERSON PR ON A.Adopter_ID = PR.ID',
    validateType: 'rowCount',
    expectedCount: 6,
    points: 300,
    successMessage: "6 successful adoptions! Thank-you cards are on their way! 🎉💌❤️"
  },

  // ── LEVEL 6: Advanced ─────────────────────────────────────────────
  {
    id: 13,
    level: 6,
    levelName: 'Level 6 — SQL Expert',
    levelEmoji: '🎓',
    title: 'Pets Needing Extra Care',
    story: "The veterinary team wants to follow up on any pet that arrived with a health issue. Find all medical reports where the diagnosis is NOT 'Healthy' so the vets can schedule check-ups.",
    task: "Select <code>Pet_id</code>, <code>Diagnosis</code>, and <code>Notes</code> from <code>MEDICAL_REPORT</code> where <code>Diagnosis</code> is <strong>not</strong> <code>'Healthy'</code>.",
    hint: "Use <code>WHERE column != 'value'</code> (or <code>&lt;&gt;</code>) for not-equal comparisons.",
    canonicalQuery: "SELECT Pet_id, Diagnosis, Notes FROM MEDICAL_REPORT WHERE Diagnosis != 'Healthy'",
    validateType: 'rowCount',
    expectedCount: 6,
    points: 400,
    successMessage: "6 pets needed extra care — and thanks to you, they all got it! 🩺💚"
  },
  {
    id: 14,
    level: 6,
    levelName: 'Level 6 — SQL Expert',
    levelEmoji: '🎓',
    title: 'The Grand Director\'s Report',
    story: "FINAL MISSION! The shelter director needs a complete report for the board meeting: every pet that is still in the shelter (not yet adopted), with their city and current status — sorted by city, then by pet name.",
    task: 'Join <code>PET</code> and <code>SHELTER</code>, show <code>Pet_name</code>, <code>City</code>, and <code>Adoption_status</code>, filter out <code>\'Adopted\'</code> pets, and order by <code>City</code> then <code>Pet_name</code>.',
    hint: "You need: a JOIN, WHERE Adoption_status != 'Adopted', and ORDER BY with two columns (City, Pet_name).",
    canonicalQuery: "SELECT P.Pet_name, S.City, P.Adoption_status FROM PET P JOIN SHELTER S ON P.Shelter_id = S.Shelter_id WHERE P.Adoption_status != 'Adopted' ORDER BY S.City, P.Pet_name",
    validateType: 'rowCount',
    expectedCount: 15,
    points: 500,
    successMessage: "INCREDIBLE! You've mastered SQL at PawShelter! You're officially a SQL Detective! 🏆🌟🎓"
  }
];
